config/routes.rb
Rails.application.routes.draw do
  
  root 'articles#index'
  resources :articles do
    member do
      get :delete
    end
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	# makes sure all the associated comments get destroyed too
	has_many(:comments, :dependent => :destroy)
	validates_length_of(:content, :minimum => 5)
	validates(:author, :presence => true)
	validates(:title, :presence => true, :length => {:minimum => 4, :maximum => 30})
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to(:article)
	validates(:commenter, :presence => true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  http_basic_authenticate_with(:name => "user", :password => "password", :only => [:index, :destory])
  rescue_from(ActiveRecord::RecordNotFound, :with => :record_not_found)

  def index
  	@all_articles = Article.all
    @time = Time.now.asctime
    @global_article = "Really cool Article Title"
    respond_to do |format|
      format.html
      format.json {render(:json => @all_articles)}
    end
  end

  def show
  	@article = Article.find(params[:id])
  end

  def edit
  	@article = Article.find(params[:id])
  end

  def new
  	@article = Article.new
  end

  def create
  	#render(:plain => params.inspect)
  	@article = Article.new(article_params)
  	if @article.save
  		#redirect_to(:action => "show", :id => @article.id)
  		flash[:notice] = "New article created successfully!"
  		redirect_to(article_path(@article.id))
  	else
      flash[:notice] = "Article didn't post. Please make sure you have enough content in each field"
  		render("new")
  	end
  end

  def update
  	@article = Article.find(params[:id])
  	if @article.update_attributes(article_params)
  		flash[:notice] = "Updated article successfully!"
  		redirect_to(article_path(@article.id))
  	else
      flash[:notice] = "Article didn't post. Please make sure you have enough content in each field"
  		render("edit")
  	end
  end

  def delete
  	@delete_article = Article.find(params[:id])
  end

  def destroy
  	subject = Article.find(params[:id]).destroy
    flash[:notice] = "Successfully deleted the article: #{subject.title}!"
  	redirect_to(articles_path)
  end
  
  private
  	# strong params!
	  # same as using params[:subject], except it
    # raises an error if :subject is not present
    # allows listed arguments to be mass assigned 
  	def article_params
  		params.require(:article).permit(:author, :title, :content)
  	end

    def record_not_found
      # render(:text => "Hmm, counldn't find that...", :status => 404)
      render("error")
      message = "Item with ID #{params[:id]} not found"
      logger.error(message)
      # redirect_to(articles_path)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
  def edit
  	@article = Article.find(params[:article_id])
  	@comment = @article.comments.find(params[:id])
  end

  def update
  	@article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  	if @comment.update_attributes(comment_params)
      # flash a hash here!
  	  redirect_to(article_path(@article))
    else
      # handle the error!
    end
  end

  def create
  	#render(:plain => params.inspect)
  	@article = Article.find(params[:article_id])
  	@comment = @article.comments.create(comment_params)
  	redirect_to(article_path(@article))
  end

  def destroy
  	@article = Article.find(params[:article_id])
  	@comment = @article.comments.find(params[:id])
  	@comment.destroy
  	redirect_to(article_path(@article))
  end

  private
	  def comment_params
		params.require(:comment).permit(:commenter, :comment)  
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |form| %>

	<p><strong>Author:</strong></p>
	
	<p><%= form.text_area(:author, :cols => 80, :rows => 1) %></p>
	
	<p><strong>Title:</strong></p>
	
	<p><%= form.text_area(:title, :cols => 80, :rows => 1) %></p>
	
	<p><strong>Content:</strong></p>
	
	<p><%= form.text_area(:content, :cols => 80, :rows => 10) %></p>

	<p><%= form.submit("Submit") %></p>

<% end %>

app/views/articles/delete.html.erb
<h1>Delete Article</h1>

<hr>
<p><strong>Author:</strong></p>

<p><%= @delete_article.author %></p>

<p><strong>Title:</strong></p>

<p><%= @delete_article.title %></p>

<p><strong>Content:</strong></p>

<p><%= @delete_article.content %></p>

<hr>

<p>
	<%= link_to("Index", articles_path) %> |
	<%= link_to("Edit", edit_article_path) %> |
	<%= link_to("Delete", @delete_article, :method => :delete, :data => {:confirm => "Are you sure?"}) %>
</p>

app/views/articles/edit.html.erb
<h1>Edit</h1>

<hr>

<%= render("form") %>

<hr>

<p>
	<%= link_to("Index", articles_path) %> |
	<%= link_to("Show", article_path) %> |
	<%= link_to("Delete") %>
</p>

app/views/articles/error.html.erb
<h1>You're looking for the wrong thing...</h1>
<%= link_to("Get out of here", articles_path) %>

app/views/articles/index.html.erb
<h1>DevHut Blog</h1>

<hr>

<p><%= link_to("Add a new article", new_article_path) %></p>

<% @all_articles.each do |art| %>

	<hr>

	<p><strong>Author:</strong></p>

	<p><%= art.author %></p>

	<p><strong>Title:</strong></p>

	<p><%= art.title %></p>

	<p><strong>Content:</strong></p>

	<p><%= art.content %></p>

	<p>
		<%= link_to("View Article", article_path(art.id)) %> |
		<%= link_to("Edit", edit_article_path(art.id)) %> |
		<%= link_to("Delete", delete_article_path(art.id)) %>
	</p>

<% end %>

app/views/articles/new.html.erb
<h1>New</h1>

<hr>

<%= render("form") %>

<hr>

<p><%= link_to("Index", articles_path) %></p>

app/views/articles/show.html.erb
<h1>Show</h1>

<p>
	<%= link_to("Index", articles_path) %> |
	<%= link_to("Edit", edit_article_path) %> |
	<%= link_to("Delete", @article, :method => :delete, :data => {:confirm => "Are you sure?"}) %>
</p>

<hr>

<p><strong>Author:</strong></p>

<p><%= @article.author %></p>

<p><strong>Title:</strong></p>

<p><%= @article.title %></p>

<p><strong>Content:</strong></p>

<p><%= @article.content %></p>

<hr>

<% @article.comments.each do |c| %>
	<p><strong><%= c.commenter %> wrote: </strong></p>
	<p><%= c.comment %></p>
	<p> <%= link_to("Edit", edit_article_comment_path(@article.id, c.id)) %> | <%= link_to("Delete", [c.article, c], :method => :delete, :data => {:confirm => "Positive?"}) %> </p>
<% end %>

<hr>
<h2>Add a comment: </h2>
<%= form_for([@article, @article.comments.build]) do |form| %>
	
	<p><strong>Commenter:</strong></p>
	
	<p><%= form.text_area(:commenter, :cols => 80, :rows => 1) %></p>
	
	<p><strong>Comment:</strong></p>
	
	<p><%= form.text_area(:comment, :cols => 80, :rows => 10) %></p>

	<p><%= form.submit("Submit Comment") %></p>

<% end %>

<hr>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= form_for([@article, @comment]) do |form| %>
	
	<p><strong>Commenter:</strong></p>
	
	<p><%= form.text_area(:commenter, :cols => 80, :rows => 1) %></p>
	
	<p><strong>Comment:</strong></p>
	
	<p><%= form.text_area(:comment, :cols => 80, :rows => 10) %></p>

	<p><%= form.submit("Submit Comment") %></p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<p><%= @time %></p>

<% if !flash[:notice].blank? %>
<h1><%= flash[:notice] %></h1>
<% end %>

<%= yield %>

</body>
</html>